### ISSUE TITLE
missing QVDs

### ISSUE THREAD

**Issue by g3l0o** [PacktPublishing/Hands-On-Business-Intelligence-with-Qlik-Sense#2]
Hi, first of all, very good book.
For the Chapter 4, when the qvf file is opened it tries to pull the data from some QVDs, these QVDs are not in the folders, to solve these I had to map the qvf to pull the data from the chapter 2 txt files. 

Could you please upload those missing QVDs, please?

**Comment by kaushiknsolanki** [comment]
Hi,
First of all thanks for identifying the issue and intimating us.
I have uploaded the QVD's in chapter 4.

Also would like to request you to share your review on amazon about your experience while reading this book.

Thanks Again.
