### ISSUE TITLE
Missing Fields

### ISSUE THREAD

**Issue by victorbertoldo** [PacktPublishing/Hands-On-Business-Intelligence-with-Qlik-Sense#3]
Hi there! On chapter 2 page 70, was mentioned that are 18 fields. But, even if I counting on calculated field (Processing Time), my model has 17 fields, extracting from Hands-On-Business-Intelligence-with-Qlik-Sense\Chapter02\Orders.xlsx

**Comment by gaurav-packt** [comment]
Please reopen if the issue persists.
